### ISSUE TITLE
Tips til å bygge Quarto fortelling i Github Action

### ISSUE THREAD

**Issue by nordmoen** [navikt/story-upload#1]
Tenkte bare å slenge inn dette som et forslag hvis noen andre lurer. Jeg ønsket ikke at output fra Quarto skulle være sjekket inn i repoet mitt så jeg lurte på om jeg kunne kjøre Quarto i en Github Action. Jeg fant de [offisielle stegene fra Quarto selv](https://github.com/quarto-dev/quarto-actions) og laget:

```yaml
name: Publiser Quarto på datamarkedsplassen

on:
    push:
        branches:
            - main
jobs:
    build-deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4
            - name: Install Quarto
              uses: quarto-dev/quarto-actions/setup@v2
              # MERK: Denne kjører "quarto render" i roten av prosjektet ditt
            - name: Render project
              uses: quarto-dev/quarto-actions/render@v2
            - name: Last opp til Datamarkedsplassen
              uses: navikt/story-upload@v1
              with:
                id: 58aa330c-3a72-470e-926f-22e029719879
                # For Quarto book så havner output i "_book", men det er avhengig av typen Quarto prosjekt
                # Man kan stille det inn manuelt med "output-dir"
                dir: _book
                team_token: ${{ secrets.TEAM_TOKEN }}
                env: prod
                public: false

```
